apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: gv00q3gtk-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/gv00q3gtk-dotnet-basic-gitops